INSERT INTO COUNTRY VALUES(1,'Europe','Macedonia');
INSERT INTO COUNTRY VALUES(2,'North America','Canada');
INSERT INTO COUNTRY VALUES(3,'Asia','Thailand');
INSERT INTO COUNTRY VALUES(4,'Africa','DRC');
INSERT INTO COUNTRY VALUES(5,'Europe','United Kingdom');

INSERT INTO AUTHOR VALUES(1,'NAME1', 'SURNAME1', 3);
INSERT INTO AUTHOR VALUES(2,'NAME2', 'SURNAME2', 1);
INSERT INTO AUTHOR VALUES(3,'NAME3', 'SURNAME3', 4);
INSERT INTO AUTHOR VALUES(4,'NAME4', 'SURNAME4', 2);
INSERT INTO AUTHOR VALUES(5,'NAME5', 'SURNAME5', 5);

INSERT INTO BOOK VALUES(1,20,'FANTASY', 'BOOK1', 2);
INSERT INTO BOOK VALUES(2,13,'BIOGRAPHY', 'BOOK2', 4);
INSERT INTO BOOK VALUES(3,10,'HISTORY', 'BOOK3', 5);
INSERT INTO BOOK VALUES(4,3,'THRILLER', 'BOOK4', 3);
INSERT INTO BOOK VALUES(5,12,'DRAMA', 'BOOK5', 1);
INSERT INTO BOOK VALUES(6,20,'FANTASY', 'BOOK6', 2);
INSERT INTO BOOK VALUES(7,13,'BIOGRAPHY', 'BOOK7', 4);
INSERT INTO BOOK VALUES(8,10,'HISTORY', 'BOOK8', 5);
INSERT INTO BOOK VALUES(9,3,'THRILLER', 'BOOK9', 3);
INSERT INTO BOOK VALUES(10,12,'DRAMA', 'BOOK10', 1);